### ISSUE TITLE
Manage GitHub projects as well

### ISSUE THREAD

**Issue by nmerget** [OpenRailAssociation/github-org-manager#81]
I would be great if we could manage GitHub [Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) as well.

Based on the configuration it could be like this:

````yaml
Project Team:
  ...
  projects:
    roadmap:
      id: 1
      role: (admin | write | read)
    backlog:
      id: 2
      role: (admin | write | read)
````

Sadly the projects have an ID string with 1. Therefore, I would suggest using a name for better understanding.
Otherwise it could lead to issues if you forget a comment:

````yaml
Project Team:
  ...
  projects:
    1: (admin | write | read) # This is the roadmap
    2: (admin | write | read) # This is the backlog
````
